### ISSUE TITLE
Website Error (NotAllowedError)

### ISSUE THREAD

**Issue by rognoni** [typicaljoe/taffydb#111]
```
Traceback (most recent call last):
  File "/base/data/home/runtimes/python/python_lib/versions/1/google/appengine/ext/webapp/_webapp25.py", line 715, in __call__
    handler.get(*groups)
  File "/base/data/home/apps/s~taffydbcom/1.365572725240658134/handlers/main.py", line 48, in get
    self.render("index.html", {"page": "main"})
  File "/base/data/home/apps/s~taffydbcom/1.365572725240658134/handlers/baserequesthandler.py", line 30, in render
    'login_url': users.create_login_url(self.request.uri),
  File "/base/data/home/runtimes/python/python_lib/versions/1/google/appengine/api/users.py", line 258, in create_login_url
    raise NotAllowedError
NotAllowedError
```

**Comment by cfaheyCurveJumper** [comment]
Seeing this too: taffydb.com (and documentation) down.

**Comment by mmikowski** [comment]
Unfortunately, only Ian has access to this server.  I will try to give him a bump.

**Comment by typicaljoe** [comment]
Fixed!

**Comment by cfaheyCurveJumper** [comment]
Awesome! Thanks!
